import turtle
from random import * 
turtle.colormode (255)
bob = turtle.Turtle ()
turtle.tracer (False)
turtle.bgcolor ("Black")

def jump (x,y):
    bob.penup()
    bob.goto(x,y)
    bob.pendown()
    
def twoEColors ():
    Color ()
    line ()
    lineTwo ()

def Color ():
    colors = ('Red', 'Silver')
    for times in range (122):
	    jump (0,0)
	    bob.width(5)
	    bob.color (colors[times%2])
	    bob.right (10)
	    bob.forward (280)
	    bob.forward (280)
	    bob.forward (285)
	    bob.forward (300)
	    bob.forward (280)
	    bob.forward (280)
	    bob.forward (285)
	    bob.forward (300)

def line ():
    colors = ('Red','Silver')
    for times in range (122):
            jump (0,-950)
            bob.width(3.5)
            bob.color (colors[times%2])
            bob.right (3)
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()

def lineTwo ():
    colors = ('Red','Silver')
    for times in range (122):
            jump (0,950)
            bob.width(3.5)
            bob.color (colors[times%2])
            bob.right (3)
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()
            bob.forward (99)
            bob.begin_fill()
            bob.circle (50)
            bob.end_fill()


